#!/bin/bash
me=$(basename $0)
sourcefile=$1
fullfile=$(pwd)/$1
importdir=~/neo4j/neo4j_docker/import/
if [ "" = "$sourcefile" ]
then
	echo "ERROR: Usage $me <jsonfile>"
	exit 1
fi
cs="cypher-shell $CYPHER_SHELL_PARAM"
echo "Importing file $sourcefile"
basefile=$(basename $sourcefile)
importfile=$importdir/$basefile
cp $sourcefile $importfile
cat ../../import_json.cypher | sed -e "s#FILE#file://$basefile#g" | cypher-shell $CYPHER_SHELL_PARAM
rm $importfile
