load csv with headers from $FILEURL as line
    merge (p:Patent {ID:toInteger(line.ID)})
    set 
		p.Jurisdiction = line.Jurisdiction,
		p.Kind = line.Kind,
		p.PublicationNumber = line.PublicationNumber,
		p.LensID = line.LensID,
		p.PublicationDate = date(line.PublicationDate),
		p.PublicationYear = toInteger(line.PublicationYear),
		p.ApplicationNumber = line.ApplicationNumber,
		p.ApplicationDate = date(line.ApplicationDate),
		p.PriorityNumbers = split(line.PriorityNumbers, ";;"),
		p.EarliestPriorityDate = date(line.EarliestPriorityDate),
		p.Title = line.Title,
		p.Applicants = split(line.Applicants,";;"),
		p.Inventors = split(line.Inventors,";;"),
		p.OwnersUS = split(line.OwnersUS, ";;" ),
		p.URL = line.URL,
		p.Type = line.Type,
		p.HasFullText = (case line.HasFullText when "yes" then true else false end),
		p.CitedbyPatentCount = toInteger(line.CitedbyPatentCount),
		p.SimpleFamilySize = toInteger(line.SimpleFamilySize),
		p.ExtendedFamilySize = toInteger(line.ExtendedFamilySize),
		p.SequenceCount = toInteger(line.SequenceCount),
		p.CPCClassifications = split(line.CPCClassifications,";;"),
		p.IPCRClassifications = split(line.IPCRClassifications,";;"),
		p.USClassifications = split(line.USClassifications,";;"),
		p.NPLCitationCount = toInteger(line.NPLCitationCount),
		p.NPLResolvedCitationCount = toInteger(line.NPLResolvedCitationCount),
		p.NPLResolvedLensIDs = split(line.NPLResolvedLensIDs, ";;"),
		p.NPLResolvedExternalIds = split(line.NPLResolvedExternalIds,";;"),
		p.NPLCitations = split(line.NPLCitations,";;")
;
